FROM nginx:alpine
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./build-federation /usr/share/nginx/html
RUN apk add \
    xorg-server \
    libxi-dev \
    libxext-dev
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]