server {
  listen       80;
  server_name  localhost;
  root   /usr/share/nginx/html;
  index  index.html index.htm;

  # Rediriger les requêtes /api vers le backend
  location /api/ {
    proxy_pass http://ciqo-api:5600;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    try_files $uri /index.html;
    add_header Cache-Control "no-store, no-cache, must-revalidate";
  }
  
  location ~ .(static)/(js|css|media)/(.+)$ {
		try_files $uri $uri/ /$1/$2/$3;
	}
}